--- fs/Makefile	2012-06-09 23:36:33.000000000 +0800
+++ fs/Makefile	2013-10-18 10:52:01.907938880 +0800
@@ -125,3 +125,4 @@
 obj-y				+= exofs/ # Multiple modules
 obj-$(CONFIG_CEPH_FS)		+= ceph/
 obj-$(CONFIG_PSTORE)		+= pstore/
+obj-$(CONFIG_YAFFS_FS)		+= yaffs2/
